### ISSUE TITLE
Deploy NuGet package task is not working for commerce

### ISSUE THREAD

**Issue by SergeyP78** [Epinova/epinova-dxp-deployment#120]
I'm getting the below error:
##[error]The variable '$resolvedCmsPackagePath' cannot be retrieved because it has not been set.

The reason is that the resolvedCmsPackagePath variable is not defined by default in DeployNuGetPackage.ps1. But it is used in a clause at line 90: if ($null -ne $resolvedCmsPackagePath -and $null -ne $resolvedCommercePackagePath). 
I suggest to initialize the variable as null by default at line 56:
$resolvedCmsPackagePath = $null

**Comment by ovelartelius** [comment]
Hi @SergeyP78 
I totally agree with you. Have done the changes and deployed v1.9.43. So try to run the task again. When the task has run you should be able to see that the task (DeployNuGetPackage) should have version 1.1.19.
Poke me again if you still get error and I will fix ASAP.
Kind regards
Ove

**Comment by SergeyP78** [comment]
Hi @ovelartelius 
Thank you for the quick fix! The commerce deployment task works now. But I found another issue: I used an incorrect url (it returned the 302 status) inside my 'Smoke test' task and got the below error:
`The property 'Response' cannot be found on this object. Verify that the property exists.  `
I guess this error is happening inside the catch block at line 77:
`                $statusCode = $_.Exception.Response.StatusCode.value__`

I don't know how to handle this, but the task had been stopped because of the error and I had to manually complete the deployment later.

Best regards,
Sergey

**Comment by ovelartelius** [comment]
Hi @SergeyP78 
Nice to hear that that last update solved your issue.
Hmmmm ok. I think we need to split this  into different things. 
1. I understand that there must be something wrong with the script that can not get the Response object. I will look into that ASAP.
2. If you have a URL that return 302. Try to change that to a URL that should response in 200. Like https://something/util/login.aspx or something like that. You can use the UrlSuffix to handle that if  you have followed the description of the setup in the blog: https://www.epinova.se/nyheter-och-blogg/utvecklarbloggen/2020/dxpdeploy-p4-setupcicd/
3. You can complete the deploy by go into https://paasportal.episerver.net/ and just click on "Complete deploy".

I have had problem my self with the SmokeTest step. So I have just stoped using it. And when I say that I fill that I should spend some time to make it better. The hard part is to change it in a way so it works with all the exceptions different projects have. But I will start find a solution for that.

I will create a new issue for the SMokeTest problem so we dont start to mix different issues in the same issue. Hope that this is ok.
Kind regards
Ove

**Comment by SergeyP78** [comment]
Thank you for the update, @ovelartelius !
Regarding your suggestions:
2. I've already changed the URL and the task works well now 👍 
3. It was a deployment to DXP integration and there was no option in the paasportal to complete or reject it :)

Best regards,
Sergey
