### ISSUE TITLE
Deploy Nuget package status updates

### ISSUE THREAD

**Issue by erdihu** [Epinova/epinova-dxp-deployment#124]
Include, if possible, status updates & warnings from the job Depliy Nuget Package where output type is Information.

**Comment by ovelartelius** [comment]
Hi @erdihu
Thanks for creating this issue. But I would like to get some more description so I really understand what you are looking for. 
Do you mean that you can see alot more information in the paas portal but when use DeployTo i Azure you can only see how many procentage that has been done? If I missunderstand you please fill in the gaps.

**Comment by erdihu** [comment]
Hi,
Yes! In the PaaS Portal there's a lot more information about the process. Is there a technical limitation that prevents showing the same information?

**Comment by ovelartelius** [comment]
Hi @erdihu 
Ok. When I created this task a couple of months ago, this information where not shown from the EpiCload module that is used to do this. But I will have a extra look if this has been changed. I get back to you.

**Comment by ovelartelius** [comment]
Hi @erdihu 
I have digged into this now and can only sadly announce that the information you want to see is not available from the EpiCloud module. But Im going to pitch this for Episerver/Optimizely so that they now that we are atleast 2 persons that wants this feature. :)

**Comment by erdihu** [comment]
Hi Ove, thanks for the response. I suspected this would be the case since I couldn't find any filtering function in the script but I'm far from a Powershell guru so I wasn't sure. Let's hope that Episerver implements this.
