### ISSUE TITLE
New option for ZDD in "Deploy NuGet package" task

### ISSUE THREAD

**Issue by jorgenhelgheim** [Epinova/epinova-dxp-deployment#149]
Could you provide an option for Zero Downtime Deployment inside task "Deploy NuGet package (EPiServer DXP)"

.EXAMPLE
        Start-EpiDeployment -ClientKey $myKey -ClientSecret $mySecret -ProjectId $projectId -TargetEnvironment Production -DeploymentPackage cms.app.1.0.0.nupkg -ZeroDownTimeMode ReadOnly
 
         Starts a deployment of a code package to Production environment with zero downtime readonly mode.
        
![image](https://user-images.githubusercontent.com/1195872/117977641-55409f80-b331-11eb-8a2c-dcae26391191.png)

**Comment by ovelartelius** [comment]
Hi @jorgenhelgheim 
ZDD has been supported in the task "Deploy Smooth To" during the beta test period. I have missed that the beta period is over. So I have now moved the ZDD parameter into the "Deploy To" task. The new version 1.11.5 include the ZDD in the "Deploy to" task. I have started to write a warning for those that use the "Deploy Smooth To" today.
Please try to use the "Deploy To" task and contact me if you get any problems. 
Regards 
Ove

**Comment by jorgenhelgheim** [comment]
Hello. Great, but..

I can not use "Deploy To" since I merge secrets from DevOps into configuration files at deploy time (per. env). Production configuration on preproduction are missing production-secrets, so I can not use "Deploy To" or Paasportal to this env. And since Episerver supports use of ZDD with Deploy nugetpackage as well, it would be nice to have this posibility in your great module aswell.

**Comment by ovelartelius** [comment]
Hi @jorgenhelgheim 
:) Since you are so nice to me I have added this feature to the DeployNugetPackage task. I don´t have a project with this setup. So I would be super happy if you could try this and get back to me with the result. The new version v1.12.0 include this new update.

**Comment by jorgenhelgheim** [comment]
Thanks Ove. :)
The DeployNugetPackage task works with ZDD. I tested this today. Thanks for this update. 

I have not tried to Reset the ZDD deployment from Devops, but I guest that is not part of the DeployNugetPackage task anyways.
