### ISSUE TITLE
Deploy nuget package warning

### ISSUE THREAD

**Issue by mikemalloy-commscope** [Epinova/epinova-dxp-deployment#156]
When using the Deploy nuget package (Episerver DXP) task I see the following warning 2 times.

##[warning]Because the Az modules have all the capabilities of AzureRM modules and more, we will retire the AzureRM modules on 29 February 2024. Learn more about the migration to Az: http://aka.ms/azpsmigrate.

**Comment by ovelartelius** [comment]
Hi @mikemalloy-commscope 
I agree and don´t like the warnings. I will give it another try to go around this problem. I was hoping that Optimizely would change there Epicloud code to handle this. 
I will give it a shot. I will get back with info...

**Comment by ovelartelius** [comment]
@mikemalloy-commscope 
In my testenvironment I was able to remove the warning. Just did a test with the latest version and I still get this warning in Azure DevOps. I will open this issue again and continue try fix this.

**Comment by ovelartelius** [comment]
Duhh!
I found a solution :) https://docs.microsoft.com/en-us/powershell/azure/faq?view=azps-6.1.0&viewFallbackFrom=azps-5.7.0#how-do-i-disable-breaking-change-warning-messages-in-azure-powershell 
Was mutch simplier than i thought. Now you should not receive these warnings @mikemalloy-commscope 
Released in v1.14.1.
/Ove and out

**Comment by mikemalloy-commscope** [comment]
Perfect, thanks so much. (Sorry for the late response)
