### ISSUE TITLE
Run in ubuntu pipeline

### ISSUE THREAD

**Issue by lars-w-pedersen** [Epinova/epinova-dxp-deployment#166]
When i try to run the task DxpDeployNuGetPackage@1 in a pipeline using "vmImage: ubuntu-latest" i get the following error:

##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

would it be possible to enable this to run in ubuntu?

**Comment by ovelartelius** [comment]
Hi @lars-w-pedersen 
The Epinova DXP deployment extension use PowerShell script to talk to DXP API. So the only supported operating system supported for this tasks is windows. So if you use `vmImage: 'windows-latest'` it will work just fine.
Regards Ove

**Comment by lars-w-pedersen** [comment]
Hi @ovelartelius 
Yes i know. But some of the other tasks i run in my pipeline are very slow on windows so I would like to be able to use ubuntu to speed up things.

**Comment by lars-w-pedersen** [comment]
So if the scripts could run using Powershell Core then it could be used in ubuntu and my pipeline would run 50% faster :)

**Comment by ovelartelius** [comment]
Aaaaa. I can not promise anything right now but will look into it.

**Comment by lars-w-pedersen** [comment]
I talked to Optimizely they might need to update a manifest or something, but they say their scripts can run in core.

**Comment by ovelartelius** [comment]
@lars-w-pedersen FYI. Have found a way to solve this. I have been able to convert 3 tasks at the moment. I will continue with more tasks. ASAP. I just wanted you to know that Im working on it :)

**Comment by lars-w-pedersen** [comment]
thanks that is great :)

**Comment by ovelartelius** [comment]
Hi @lars-w-pedersen. Now the v2.0.1 i released and I would be happy if you could test the new v2 tasks that now are cross platform supportive. So if you use YAML you just change Dxp*@1 => Dxp*@2.
I have tested all tasks in both windows/ubuntu/macos and have not found any problem. But I want to see that it works for everybody. 
Please contact me if you need any help.

**Comment by lars-w-pedersen** [comment]
Hi @ovelartelius that is great, sadly i do not have access to a DXP environment anymore. It was a Beta environment which is now closed. But i am sure that i will get the opportunity again soon, and then i will make sure to use v2

**Comment by ovelartelius** [comment]
@lars-w-pedersen ok. Understand! I will close this issue now and just feel free to create a new if something pops-up.
