### ISSUE TITLE
DownloadDxp(DbN)Blobs Join-Parts doesn't support UNC paths

### ISSUE THREAD

**Issue by peter-tornqvist-kan** [Epinova/epinova-dxp-deployment#181]
The start of an UNC path ("\\\\") is removed by the Join-Parts method which makes Test-Path fail to find existing files.

Suggested solution: remove the `trim($Separator)` in Join-Parts. In this specific case it is probably not necessary (at least not on Windows)

Bonus: add a Replace to this line to convert URI style paths to UNC style paths:
`$filePath = (Join-Parts -Separator '\' -Parts $downloadFolder, $blobContent.Name.Replace("/", "\")) `

**Comment by ovelartelius** [comment]
@peter-tornqvist-kan  Thanks for your finding and tips. I will look into that ASAP.

**Comment by ovelartelius** [comment]
@peter-tornqvist-kan I have done the changes that you requested. Should be a new version v0.1.1 published to PowerShellGallery. Hope that helps you.
Cheers!

**Comment by peter3** [comment]
@ovelartelius excellent, thank you very much!
