### ISSUE TITLE
Deploy NuGet package fails if Source Alias has spaces

### ISSUE THREAD

**Issue by tomludd** [Epinova/epinova-dxp-deployment#213]
When artifact path contains whitespace "Deploy NuGet package" if fails as it does not use the whole path.
Path should be 'D:\a\r1\a\_Malorama - Site\drop' not 'D:\a\r1\a\_Malorama'

Example Source alias: '_Malorama - Site'
![image](https://user-images.githubusercontent.com/13499493/158159536-671cd8fb-54ed-458e-a3ca-d90c67f2ff85.png)

Error message:
##[error]Get-ChildItem : Cannot find path 'D:\a\r1\a\_Malorama' because it does not exist.

![image](https://user-images.githubusercontent.com/13499493/158158670-08766d92-1780-41fd-bb7e-dd604b9124cc.png)

**Comment by ovelartelius** [comment]
rename?

**Comment by ovelartelius** [comment]
v2.2.14
