### ISSUE TITLE
Example pipelines for ubuntu?

### ISSUE THREAD

**Issue by peter3** [Epinova/epinova-dxp-deployment#221]
Hi, I've been trying to use the example pipelines as a base for our own deploy scripts to DXP Linux (specifically the Develop-Inte.yaml), but it has some issues I have been unable to resolve. Are you planning on creating example files that works with ubuntu as well?

Thanks

**Comment by ovelartelius** [comment]
Hi @peter3 ! Yes that is the plan. You are talking about build and release .Net5 or 6 project on ubuntu and release to a Linux DXP instance right?

**Comment by peter3** [comment]
Yes, that is what I am currently working with :)

**Comment by ovelartelius** [comment]
I have created this example yml now. 
https://github.com/Epinova/epinova-dxp-deployment/blob/feature/221-ubuntu-pipeline/Pipelines/Develop-Inte-ubuntu.yml
https://github.com/Epinova/epinova-dxp-deployment/blob/feature/221-ubuntu-pipeline/Pipelines/azure-pipelines-steps.yml
I have not been able to test these yeat. But a almost identical version of these works in another project. Please try and get back to me with info how it worked. 
The first "Develop-Inte-Ubuntu.yml" is the file that you setup in Azure DevOps. It will load the other one as a template. There could be nuget/npm/solution names/ etc that needs to be changed so it fit your project.

**Comment by ovelartelius** [comment]
@peter3 did the yml examples help you? :)

**Comment by peter3** [comment]
@ovelartelius I've just noticed that you've done this. Great job! I will try it out during next week. I've already created our own pipelines, but still nice to check out how you've solved it :)
