### ISSUE TITLE
DeployNuGetPackage: DropPath none support for spaces in foldernames

### ISSUE THREAD

**Issue by ovelartelius** [Epinova/epinova-dxp-deployment#222]
Ex: -DropPath D:\a\r1\a/_Something - public web/something.cms.ubuntu
Needs to be -DropPath "D:\a\r1\a/_Something - public web/something.cms.ubuntu" to work.

Error message:
2022-06-23T11:24:46.3237692Z ##[error]D:\a\_tasks\DxpDeployNuGetPackage_2bc993e5-c27c-4a24-aeaf-0fc403debc8d\2.2.18\DeployNuGetPackage.ps1 : A positional 
parameter cannot be found that accepts argument 'web/something.cms.ubuntu'.

**Comment by oyvindwh** [comment]
Is this the same error @ovelartelius? There are no spaces and worked with 2.2.18, failes with 2.2.19.

![image](https://user-images.githubusercontent.com/106393/175476322-f5440997-b3ac-43f1-8c2c-3885239990f3.png)

**Comment by tomludd** [comment]
@oyvindwh seems like this has only been tested on windows agents, not ubuntu. As a temporary workaround use windows latest as deployment agent.

![image](https://user-images.githubusercontent.com/13499493/175493398-a443d619-a1d6-45d5-be5d-024a684e400e.png)

**Comment by oyvindwh** [comment]
That is correct, we changed the agent to run on windows latest and that fixed the issue.

**Comment by tomludd** [comment]
@oyvindwh this ubuntu agents should be working again now, #226 is a rollback

**Comment by ovelartelius** [comment]
@oyvindwh Hi. I have now release the DXP extension v2.2.19 that will contain the task DeployNuGetPackage v2.2.20. This release is a rollback of the erroneous code I release in the DXP extension v2.2.18.
Sorry about this!
Now you can go back to use ubuntu.

**Comment by tomludd** [comment]
@ovelartelius I think we should support spaces in filename, it just went bad last time.

**Comment by ovelartelius** [comment]
I understand the problem @tomludd. But it was not that simple to fix. I will create a new task for this and see if I can find a solution with new fresh eyes after vacation....
