### ISSUE TITLE
Question - Deploy nuget package

### ISSUE THREAD

**Issue by mikemalloy-commscope** [Epinova/epinova-dxp-deployment#23]
On the Deploy nuget package task. Is it possible to change the task to upload ALL nupkg files that are in the drop folder? My Build pipeline generates Cms and Commerce nupkg.

**Comment by ovelartelius** [comment]
Right now Im writing some documentation and blog posts. I will look into this asap.

**Comment by ovelartelius** [comment]
Solved in v1.1.4
