### ISSUE TITLE
Publish-Package : Cannot bind argument to parameter 'PackageFile' because it is null.

### ISSUE THREAD

**Issue by yophen** [Epinova/epinova-dxp-deployment#230]
Using windows agent to deploy a nuget package to Integration. The build artifact seems ok (contains the nuget package), but I keep getting this error with running the DxpDeployNuGetPackage task:
"Publish-Package : Cannot bind argument to parameter 'PackageFile' because it is null."
It feels like the artifact is not found (due to the null reference), but the drop path to the artifact seems ok.
The "Loaded cms package:" output is empty btw.
What could be causing this error?

**Comment by ovelartelius** [comment]
Hi @yophen 
What is the name of the artifact file? There is pattern that the script is using to find the artifact file. Ex: "*.$PackageType.*.nupkg". So your file should have the name like "something.cms.version.nupkg". Other real example is: "Website.cms.app.20220627.1.nupkg"
Kind regards
Ove

**Comment by yophen** [comment]
Yes! I skimmed through some of the other issues and came across a similar one where you pointed out the importance of name formatting of the package. It was missing the "website"-part. Changed the package name and it fixed the issue. Thank you for getting back to me.

**Comment by ovelartelius** [comment]
Nice! No problem! Im glad that I can help!
