### ISSUE TITLE
Additional Development Environments (ADE) and deploy

### ISSUE THREAD

**Issue by oyvindwh** [Epinova/epinova-dxp-deployment#233]
Optimizely has a feature for Linux containers called ADE where the client can have more than three default environments Integration, PreProduction and Production. See attached image for ADE1.

We would like to use the dxp deployment extension for deploying to this 4'th environment and not use powershell, but if I'm not wrong these environments are static in the extension?

Any plans for supporting more environments in the very near feature? An option could be to have Other in the dropdown and a textfield/list to type the name of additional environments?

![MicrosoftTeams-image](https://user-images.githubusercontent.com/106393/189121009-f80977e5-6a47-439b-87d2-3afb59b62b53.png)

**Comment by ovelartelius** [comment]
Hi @oyvindwh 
I did not know this. I will have a look and get back to you ASAP.
Cheers!

**Comment by ovelartelius** [comment]
Hi @oyvindwh 
I will try to implement the "Other" function for you. But can you be my testpilot? I have no Linux environments that I can test on but want to help you out. What do you say? :|

**Comment by oyvindwh** [comment]
I do not have the 4'th environment, but we have a client that has it so I can ask them. I guess it would be possible to write one of the default environment names just for the first verification. If you implement it,  we can test! Thanks.

**Comment by ovelartelius** [comment]
Hi @oyvindwh 
v2.3.0 is now published supporting Target/Source environment ADE1, ADE2, ADE3.
Please try and come back with the result :)

**Comment by oyvindwh** [comment]
Nice, will give feedback after testing! Thanks for implementing a fix so fast 🙂

**Comment by ovelartelius** [comment]
Hi @oyvindwh 
Have you had time to try deploy to ADE1?

**Comment by oyvindwh** [comment]
Not yet, the client is about to move from TeamCity / Octopus to DevOps so they will need some more time. I will ping you when tested.

**Comment by ovelartelius** [comment]
I will close this issue.
