### ISSUE TITLE
DeployTo - SourceApp error

### ISSUE THREAD

**Issue by mikemalloy-commscope** [Epinova/epinova-dxp-deployment#24]
For the DeployTo task I am choosing SourceApp: cms, commerce

I receive the error:

##[error]Cannot validate argument on parameter 'SourceApp'. The argument "cms, commerce" does not belong to the set "cms,commerce" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

I think the value of SourceApp needs to remove the space?
So "cms, commerce" becomes "cms,commerce"

**Comment by ovelartelius** [comment]
Right now Im writing some documentation and blog posts. I will look into this asap.

**Comment by ovelartelius** [comment]
This fix should now be released in v1.0.8. More testing with commerce will be done asap.

**Comment by mikemalloy-commscope** [comment]
Thank you for the change. I am still getting the same error.
When editing the task the drop-down indicates: cms,commerce
But, I noticed that the YAML indicates: SourceApp: 'cms, commerce'
