### ISSUE TITLE
Deploy NuGet packages resolved path

### ISSUE THREAD

**Issue by mikemalloy-commscope** [Epinova/epinova-dxp-deployment#30]
Can you change the pattern to support the [code package format](https://world.episerver.com/documentation/developer-guides/digital-experience-platform/deploying/episerver-digital-experience-cloud-deployment-api/deploy-using-code-packages/code-packages/)?

`<app name>.<package type>.app.<version>.nupkg`

For example, my filenames look like...
cms.app.1.0.11274.nupkg
commerce.app.1.0.11274.nupkg

`$resolvedCmsPackagePath = Get-ChildItem -Path $dropPath -Filter *.cms.*.nupkg`
`$resolvedCommercePackagePath = Get-ChildItem -Path $dropPath -Filter *.commerce.*.nupkg`

_I'm seeing the error:_

##[error]Could not find the cms package in location D:\a\r1\a\_commscope-app-Integration\DXP-Deployment-Package.

##[error]Could not find the cms package in location D:\a\r1\a\_commscope-app-Integration\DXP-Deployment-Package.

**Comment by ovelartelius** [comment]
That is strange. My is "Xxx.Yyy.cms.app.20200505.6.nupkg" for example and it works. But of course I will have a look at it ASAP. 
Im sorry that you are my test guy at the moment. My problem is that I don´t have any commerce project to test/play with.

**Comment by ovelartelius** [comment]
Hi Mike. We did a test this morning and deployed a cms,commerce release to DXP. It found and uploaded both nupkg. Yesterday I added better debug info in the task. So if it does not find a nupkg in the DropFolder it should list all the files that are in the DropFolder. So in your case it should now list all the files that are in D:\a\r1\a_commscope-app-Integration\DXP-Deployment-Package. Can you see that the nupkg files is in that DropPath?

**Comment by mikemalloy-commscope** [comment]
I think the Stop action here is preventing the additional debug info from showing.

`Write-Error "Could not find the cms package in location $dropPath." -ErrorAction Stop`

**Comment by ovelartelius** [comment]
O crap! I fix asap.

**Comment by ovelartelius** [comment]
Now it shows the files in the dropfolder if it can´t find the file(s):
2020-05-06T18:41:30.2779355Z Following files found in location D:\a\r1\a/_Website-CI/drop : Website.cms.app.20200430.2.nupkg
2020-05-06T18:41:30.2829802Z ##[error]Could not find the commerce package in location D:\a\r1\a/_Website.NET-CI/drop.
In this case I only got a cms package but set the DeployNuGetPackage to look for a commerce package.

**Comment by mikemalloy-commscope** [comment]
It's showing the cms and commerce files...

Cms PackagePath: 

Following files found in location D:\a\r1\a\_commscope-app-Integration\DXP-Deployment-Package\ : cms.app.1.0.11414.nupkg commerce.app.1.0.11414.nupkg

##[error]Could not find the cms package in location D:\a\r1\a\_commscope-app-Integration\DXP-Deployment-Package\.

##[error]Could not find the cms package in location D:\a\r1\a\_commscope-app-Integration\DXP-Deployment-Package\.

**Comment by ovelartelius** [comment]
Ok I see the problem now. Your name on the files does not contain the "AppName". In the documentation from Episerver they say the pattern should be "[AppName].[PackageType].app.[Version].nupkg". So your cms file should have the name ex: Website.cms.app.1.0.11414.nupkg and commerce file: Website.commerce.app.1.0.11414.nupkg.
So the filter in the DeployNuGetPackage task is "*.cms.*.nupkg" and "*.commerce.*.nupkg". And your file(s) does not have the dot between "AppName" and "PackageType" since there is no "AppName" at all.
So change your build pipeline so that it follow the pattern described above and it should work. 
Let me know how it goes either good or bad news!

**Comment by mikemalloy-commscope** [comment]
That did it, thanks so much!
