### ISSUE TITLE
DeployNuGetPackage.ps1 (2.9.6) throws when trying to call [System.Convert]::ToBoolean($RunBenchmark)

### ISSUE THREAD

**Issue by walleboom** [Epinova/epinova-dxp-deployment#328]
DeployNuGetPackage.ps1 (2.9.6) throws when trying to call [System.Convert]::ToBoolean($RunBenchmark)
```
2024-10-25T15:04:58.3151202Z ##[error]Exception calling "ToBoolean" with "1" argument(s): "String was not recognized as a valid Boolean."
At D:\a\_tasks\DxpDeployNuGetPackage_2bc993e5-c27c-4a24-aeaf-0fc403debc8d\2.9.6\DeployNuGetPackage.ps1:36 char:5

2024-10-25T15:04:58.3154164Z ##[error]Exception calling "ToBoolean" with "1" argument(s): "String was not recognized as a valid Boolean."
At D:\a\_tasks\DxpDeployNuGetPackage_2bc993e5-c27c-4a24-aeaf-0fc403debc8d\2.9.6\DeployNuGetPackage.ps1:36 char:5

2024-10-25T15:04:58.3156520Z ##[error]+     $runBenchmark = [System.Convert]::ToBoolean($RunBenchmark)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : FormatException
 

2024-10-25T15:04:58.3158413Z ##[error]+     $runBenchmark = [System.Convert]::ToBoolean($RunBenchmark)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : FormatException
```

**Comment by ovelartelius** [comment]
Thanks for reporting this @walleboom. 
What Agent pool and agent specification are you using? Is it yaml or classic release pipeline you are using?
Im asking because I have not been able to recreate this issue.

**Comment by walleboom** [comment]
Azure Pipelines, windows-latest in Classic Release PipelineOn 28 Oct 2024, at 14:41, Ove Lartelius ***@***.***> wrote:﻿
Thanks for reporting this @walleboom.
What Agent pool and agent specification are you using? Is it yaml or classic release pipeline you are using?
Im asking because I have not been able to recreate this issue.

**Comment by ovelartelius** [comment]
@walleboom Can´t see your comment. Can you please try again?

**Comment by walleboom** [comment]
Azure Pipelines, windows-latest in Classic 😊

**Comment by ovelartelius** [comment]
Strange! I just tried that and did not get any errors. But I have released a new version now. Can you do a new release and see if you get the same error? Make sure that you create a new release, otherwise it will still use the old version.
If you get the same error, is it possible to get more information from the log for the task that fails? You can send it ove.lartelius@epinova.se if you don´t want to publish it here.

**Comment by ovelartelius** [comment]
Is this still a problem for you @walleboom ?
