### ISSUE TITLE
[error]The current operating system is not capable of running this task. ...

### ISSUE THREAD

**Issue by MineshS** [Epinova/epinova-dxp-deployment#333]
We are seeing the following error 

##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

We have tried using the latest for both windows and ubuntu agents 

2.10.0 Works fine, 2.11.2 is the version with issues

**Comment by ovelartelius** [comment]
Hi! Are you using Agent pool Azure Pipelines or self hosted?
The DXP extension v2.11.2 is using Node v20.1. Old DXP extension version v2.10 was using Node 10 and we started to get warnings and requested to upgrade.

**Comment by MineshS** [comment]
Hi Ove, 

We are using Azure Pool and not self hosted, I can see some tests failed as part of your PR were any of these related ? 

Minesh

**Comment by ovelartelius** [comment]
No they are not related. I have just tested both with windows latest and ubuntu latest and it works fine.
![image](https://github.com/user-attachments/assets/8603b041-a587-44cb-acce-2373e10ce512)
I will test run the task "Deploy to" again (that you used in your example) and see if I find anything. BRB

**Comment by ovelartelius** [comment]
Found the error.
![image](https://github.com/user-attachments/assets/f1942d19-a10f-442b-9008-c183d0f26c7f)
Will make a hot fix ASAP. Ping you when it is out. So sorry for the trouble! :(

**Comment by MineshS** [comment]
Perfect thank you very much

**Comment by ovelartelius** [comment]
v2.11.3 is out now. I started Deploy to that failed earlier and now it should work.
![image](https://github.com/user-attachments/assets/73c09f0e-36d7-48ff-abb2-d698b330bdf1)
If it fails again it could be that the task is not reloaded. Sometimes the old version is "cached" in the snapshot of pipeline. In that case you may need to create a new pipeline so you get the latest version of the task.

**Comment by ovelartelius** [comment]
Hi @MineshS 
Are you happy with the fix? Any problems or is everything working fine now?

**Comment by MineshS** [comment]
Yes thank you @ovelartelius  this is working again now for us :)
