### ISSUE TITLE
[error]A supported task execution handler was not found...

### ISSUE THREAD

**Issue by kria** [Epinova/epinova-dxp-deployment#338]
FYI similar to #333 our deploys started failing today as well, but with a different error message:
_[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'._

This was on an on-prem Azure DevOps Server 2022.1 with 3.225.0 agents. After upgrading to DevOps Server 2022.2 and 3.238.0 agents, it works once more.

**Comment by ovelartelius** [comment]
Hi @kria 
So problem solved and everything is working fine now?

**Comment by kria** [comment]
Yes, all good now. Just wanted to share the fix for anyone else having the same issue.
