### ISSUE TITLE
ExportDb - timeout

### ISSUE THREAD

**Issue by mikemalloy-commscope** [Epinova/epinova-dxp-deployment#41]
How does the timeout work? I see you have timeout as an input but I don't see it used anywhere in the code.

**Comment by ovelartelius** [comment]
There is a loop in the script (Helper.ps1) that checks if the elapsed time has reached the specified time and then break.
`if ($sw.Elapsed.TotalSeconds -ge $timeout) { break }`
It will not cancel the export. There is no function to tell DXP/Azure to cancel the export in the background. But for the task it will stop wait for a success status response and finish the task with a timeout error.
Did it answer you question?

**Comment by mikemalloy-commscope** [comment]
Yes, thanks.
