### ISSUE TITLE
Status output

### ISSUE THREAD

**Issue by mickeb** [Epinova/epinova-dxp-deployment#58]
Hey,

Nice work with the deployment scripts!

Any particular reason for not outputting `$status.status`  in the error messages below? It would help with troubleshooting.

https://github.com/Epinova/epinova-dxp-deployment/blob/77485a09fab5e4e95bf52340013df3e5cc207ea7/src/DeployNuGetPackage/DeployNuGetPackage.ps1#L108-L116

**Comment by ovelartelius** [comment]
Hi Mikael

Thx!

The only reason it is not there is because I have not thought about it :) I fix.
